; PlatformIO Project Configuration
; RoboArm - 6-DOF Robot Arm Controller

[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
    Servo
    Wire
